swagger: '2.0'
info:
  version: 0.0.0
  title: The Star Wars API
  description: >- 
    API Description for supermodel.io demo â€“ https://github.com/supermodel/starwars.

paths:
  '/films/{id}':
    get: 
      summary: Retireve a Specific Film
      parameters:
        - name: id
          in: path
          required: true
          type: string      
      responses:
        200:
          description: Film
          schema:
            $ref:  '#/definitions/supermodelIoStarwarsCoreFilm'

# DO NOT EDIT
# This definitions section is automatically generated by supermodel.io
#
# http://supermodel.io
# https://github.com/supermodel/supermodel-cli
definitions:
  supermodelIoStarwarsCoreFilm:
    title: Film
    description: >-
      A Star Wars film


      **NOTE**: _This model is a modified version of https://swapi.co/ `Film`
      schema_
    type: object
    properties:
      releaseDate:
        format: date
        type: string
        description: The release date at original creator country.
        example: '1977-05-25'
      vehicles:
        type: array
        description: The vehicles featured within this film.
        items:
          $ref: '#/definitions/supermodelIoStarwarsCoreVehicle'
      episodeId:
        type: number
        description: The episode number of this film.
      planets:
        type: array
        description: The planets featured within this film.
        items:
          $ref: '#/definitions/supermodelIoStarwarsCorePlanet'
      starships:
        type: array
        description: The starships featured within this film.
        items:
          $ref: '#/definitions/supermodelIoStarwarsCoreStarship'
      producer:
        type: string
        description: The producer(s) of this film.
        example: 'Gary Kurtz, Rick McCallum'
      title:
        type: string
        description: The title of this film.
        example: A New Hope
      species:
        type: array
        description: The species resources featured within this film.
        items:
          $ref: '#/definitions/supermodelIoStarwarsCoreSpecies'
      director:
        type: string
        description: The director of this film.
        example: George Lucas
      characters:
        type: array
        description: The people resources featured within this film.
        items:
          $ref: '#/definitions/supermodelIoStarwarsCorePerson'
      openingCrawl:
        type: string
        description: The opening crawl text at the beginning of this film.
        example: "It is a period of civil war.\r\nRebel spaceships, striking\r\nfrom a hidden base, have won\r\ntheir first victory against\r\nthe evil Galactic Empire.\r\n\r\nDuring the battle, Rebel\r\nspies managed to steal secret\r\nplans to the Empire's\r\nultimate weapon, the DEATH\r\nSTAR, an armored space\r\nstation with enough power\r\nto destroy an entire planet.\r\n\r\nPursued by the Empire's\r\nsinister agents, Princess\r\nLeia races home aboard her\r\nstarship, custodian of the\r\nstolen plans that can save her\r\npeople and restore\r\nfreedom to the galaxy...."
    required:
      - title
      - episodeId
      - openingCrawl
      - director
      - producer
      - releaseDate
      - characters
      - planets
      - starships
      - vehicles
      - species
  supermodelIoStarwarsCorePerson:
    title: Person
    type: object
    description: >-
      An individual person or character within the Star Wars universe.


      **NOTE**: _This model is a modified version of https://swapi.co/ `Person`
      schema_
    properties:
      starships:
        description: Starships that this person has piloted
        type: array
        items:
          $ref: '#/definitions/supermodelIoStarwarsCoreStarship'
      eyeColor:
        description: The eye color of this person.
        type: string
      name:
        description: The name of this person.
        type: string
      mass:
        description: The mass of this person in kilograms.
        type: string
      gender:
        description: The gender of this person (if known).
        type: string
      films:
        description: Films that this person has been in.
        type: array
        items:
          $ref: '#/definitions/supermodelIoStarwarsCoreFilm'
      species:
        description: Species that this person is.
        type: array
        items:
          $ref: '#/definitions/supermodelIoStarwarsCoreSpecies'
      height:
        description: The height of this person in meters.
        type: string
      hairColor:
        description: The hair color of this person.
        type: string
      vehicles:
        description: Vehicles that this person has piloted
        type: array
        items:
          $ref: '#/definitions/supermodelIoStarwarsCoreVehicle'
      skinColor:
        description: The skin color of this person.
        type: string
      birthYear:
        description: >-
          The birth year of this person. BBY (Before the Battle of Yavin) or ABY
          (After the Battle of Yavin).
        type: string
      homeworld:
        description: The planet that this person was born on.
        allOf:
          - $ref: '#/definitions/supermodelIoStarwarsCorePlanet'
    required:
      - name
      - height
      - mass
      - hairColor
      - skinColor
      - eyeColor
      - birthYear
      - gender
      - homeworld
      - films
      - species
      - vehicles
      - starships
    example:
      name: Luke Skywalker
      height: '172'
      mass: '77'
      hairColor: blond
      skinColor: fair
      eyeColor: blue
      birthYear: 19BBY
      gender: male
      homeworld: {}
      films: []
      species: []
      vehicles: []
      starships: []
  supermodelIoStarwarsCorePlanet:
    title: Planet
    type: object
    description: >-
      A large mass, planet or planetoid in the Star Wars Universe.


      **NOTE**: _This model is a modified version of https://swapi.co/ `Planet`
      schema_
    properties:
      orbitalPeriod:
        description: >-
          The number of standard days it takes for this planet to complete a
          single orbit of its local star.
        type: string
      climate:
        description: The climate of this planet. Comma-seperated if diverse.
        type: string
      name:
        description: The name of this planet.
        type: string
      rotationPeriod:
        description: >-
          The number of standard hours it takes for this planet to complete a
          single rotation on its axis.
        type: string
      films:
        description: An array of Films that this planet has appeared in.
        type: array
        items:
          $ref: '#/definitions/supermodelIoStarwarsCoreFilm'
      residents:
        description: An array of Peoples that live on this planet.
        type: array
        items:
          $ref: '#/definitions/supermodelIoStarwarsCorePerson'
      gravity:
        description: A number denoting the gravity of this planet. Where 1 is normal.
        type: number
      terrain:
        description: the terrain of this planet. Comma-seperated if diverse.
        type: string
      population:
        description: The average population of sentient beings inhabiting this planet.
        type: string
      diameter:
        description: The diameter of this planet in kilometers.
        type: string
      surfaceWater:
        description: >-
          The percentage of the planet surface that is naturally occuring water
          or bodies of water.
        type: string
    required:
      - name
      - rotationPeriod
      - orbitalPeriod
      - diameter
      - climate
      - gravity
      - terrain
      - surfaceWater
      - population
      - residents
      - films
    example:
      name: Tatooine
      rotationPeriod: '23'
      orbitalPeriod: '304'
      diameter: '10465'
      climate: arid
      gravity: 1 standard
      terrain: desert
      surfaceWater: '1'
      population: '200000'
      residents: []
      films: []
  supermodelIoStarwarsCoreSpecies:
    title: Species
    description: >-
      A species within the Star Wars universe



      **NOTE**: _This model is a modified version of https://swapi.co/ `Species`
      schema_
    type: object
    properties:
      eyeColors:
        type: string
        description: >-
          A comma-seperated string of common eye colors for this species, none
          if this species does not typically have eyes.
      skinColors:
        type: string
        description: >-
          A comma-seperated string of common skin colors for this species, none
          if this species does not typically have skin.
      classification:
        type: string
        description: The classification of this species.
      designation:
        type: string
        description: The designation of this species.
      people:
        type: array
        description: An array of Persons that are a part of this species.
        items:
          $ref: '#/definitions/supermodelIoStarwarsCorePerson'
      name:
        type: string
        description: The name of this species.
      films:
        type: array
        description: An array of Films that this species has appeared in.
        items:
          $ref: '#/definitions/supermodelIoStarwarsCoreFilm'
      averageLifespan:
        type: string
        description: The average lifespan of this species in years.
      averageHeight:
        type: string
        description: The average height of this person in centimeters.
      homeworld:
        type: string
        description: The planet that this species originates from.
      language:
        type: string
        description: The language commonly spoken by this species.
      hairColors:
        type: string
        description: >-
          A comma-seperated string of common hair colors for this species, none
          if this species does not typically have hair.
    required:
      - name
      - classification
      - designation
      - averageHeight
      - averageLifespan
      - hairColors
      - skinColors
      - eyeColors
      - homeworld
      - language
      - people
      - films
    example:
      name: Human
      classification: mammal
      designation: sentient
      average_height: '180'
      skinColors: 'caucasian, black, asian, hispanic'
      hairColors: 'blonde, brown, black, red'
      eyeColors: 'brown, blue, green, hazel, grey, amber'
      averageLifespan: '120'
      homeworld: {}
      language: Galactic Basic
      people: []
      films: []
  supermodelIoStarwarsCoreStarship:
    title: Starship
    type: object
    description: >-
      A single transport craft that has hyperdrive capability.


      **NOTE**: _This model is a modified version of https://swapi.co/
      `Starship` schema_
    properties:
      passengers:
        description: The number of non-essential people this starship can transport.
        type: string
      length:
        description: The length of this starship in meters.
        type: string
      starshipClass:
        description: >-
          The class of this starship, such as Starfighter or Deep Space Mobile
          Battlestation.
        type: string
      cargoCapacity:
        description: The maximum number of kilograms that this starship can transport.
        type: string
      films:
        description: An array of Films that this starship has appeared in.
        type: array
        items:
          $ref: '#/definitions/supermodelIoStarwarsCoreFilm'
      cost:
        description: 'The cost of this starship new, in galactic credits.'
        type: string
      model:
        description: >-
          The model or official name of this starship. Such as T-65 X-wing or
          DS-1 Orbital Battle Station.
        type: string
      maxAtmospheringSpeed:
        description: >-
          The maximum speed of this starship in atmosphere. n/a if this starship
          is incapable of atmosphering flight.
        type: string
      crew:
        description: The number of personnel needed to run or pilot this starship.
        type: string
      hyperdriveRating:
        description: The class of this starships hyperdrive.
        type: string
      name:
        description: 'The name of this starship. The common name, such as Death Star.'
        type: string
      consumables:
        description: >-
          The maximum length of time that this starship can provide consumables
          for its entire crew without having to resupply.
        type: string
      pilots:
        description: An array of People that this starship has been piloted by.
        type: array
        items:
          $ref: '#/definitions/supermodelIoStarwarsCorePerson'
      manufacturer:
        description: The manufacturer of this starship. Comma seperated if more than one.
        type: string
      MGLT:
        description: >-
          The Maximum number of Megalights this starship can travel in a
          standard hour. A Megalight is a standard unit of distance and has
          never been defined before within the Star Wars universe. This figure
          is only really useful for measuring the difference in speed of
          starships. We can assume it is similar to AU, the distance between our
          Sun (Sol) and Earth.
        type: string
    required:
      - name
      - model
      - manufacturer
      - cost
      - length
      - maxAtmospheringSpeed
      - crew
      - passengers
      - cargoCapacity
      - consumables
      - hyperdriveEating
      - MGLT
      - starshipClass
      - pilots
      - films
    example:
      name: Death Star
      model: DS-1 Orbital Battle Station
      manufacturer: 'Imperial Department of Military Research, Sienar Fleet Systems'
      cost: '1000000000000'
      length: '120000'
      maxAtmospheringSpeed: n/a
      crew: '342953'
      passengers: '843342'
      cargo_capacity: '1000000000000'
      consumables: 3 years
      hyperdriveRating: '4.0'
      MGLT: '10'
      starship_class: Deep Space Mobile Battlestation
      pilots: []
      films: []
  supermodelIoStarwarsCoreVehicle:
    title: Vehicle
    type: object
    description: >-
      A single transport craft that does not have hyperdrive capability


      **NOTE**: _This model is a modified version of https://swapi.co/ `Vehicle`
      schema_
    properties:
      passengers:
        description: The number of non-essential people this vehicle can transport.
        type: string
      length:
        description: The length of this vehicle in meters.
        type: string
      name:
        description: 'The name of this vehicle. The common name, such as Sand Crawler.'
        type: string
      cargoCapacity:
        description: The maximum number of kilograms that this vehicle can transport.
        type: string
      films:
        description: An array of Film URL Resources that this vehicle has appeared in.
        type: array
        items:
          $ref: '#/definitions/supermodelIoStarwarsCoreFilm'
      cost:
        description: 'The cost of this vehicle new, in galactic credits.'
        type: string
      model:
        description: >-
          The model or official name of this vehicle. Such as All Terrain Attack
          Transport.
        type: string
      maxAtmospheringSpeed:
        description: The maximum speed of this vehicle in atmosphere.
        type: string
      vehicleClass:
        description: 'The class of this vehicle, such as Wheeled.'
        type: string
      crew:
        description: The number of personnel needed to run or pilot this vehicle.
        type: string
      consumables:
        description: >-
          The maximum length of time that this vehicle can provide consumables
          for its entire crew without having to resupply.
        type: string
      pilots:
        description: >-
          An array of People URL Resources that this vehicle has been piloted
          by.
        type: array
        items:
          $ref: '#/definitions/supermodelIoStarwarsCorePerson'
      manufacturer:
        description: The manufacturer of this vehicle. Comma seperated if more than one.
        type: string
    required:
      - name
      - model
      - manufacturer
      - cost
      - length
      - maxAtmospheringSpeed
      - crew
      - passengers
      - cargoCapacity
      - consumables
      - vehicleClass
      - pilots
      - films
    example:
      name: X-34 landspeeder
      model: X-34 landspeeder
      manufacturer: SoroSuub Corporation
      cost: '10550'
      length: '3.4'
      maxAtmospheringSpeed: '250'
      crew: '1'
      passengers: '1'
      cargo_capacity: '5'
      consumables: unknown
      vehicleClass: repulsorcraft
      pilots: []
      films: []

